name: M3U Dosya Birleştirici

on:
  push:
    branches:
      - main  # Ana branch üzerine push yapıldığında çalışır
  workflow_dispatch:  # Manuel olarak çalıştırılabilir

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Ubuntu üzerinde çalıştırılacak
    steps:
      - name: GitHub Repository Checkout
        uses: actions/checkout@v2  # Repo'yu çek

      - name: Set up Python 3.x
        uses: actions/setup-python@v4  # Python ortamını kur
        with:
          python-version: '3.x'  # Python versiyonunu belirt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # pip güncelleme
          pip install requests  # requests kütüphanesini yükleme

      - name: Run Python script
        run: |
          python your_script_name.py  # Python kodunu çalıştır

      - name: Upload the merged M3U playlist
        uses: actions/upload-artifact@v3
        with:
          name: playlist
          path: playlist.m3u  # 'playlist.m3u' dosyasını artefakt olarak yükle
