name: Trigger Workflows from Other Repos

on:
  schedule:
    - cron: "0 */2 * * *"  # Her 2 saatte bir çalışır
  workflow_dispatch:  # Manuel olarak çalıştırılabilir

jobs:
  trigger-other-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger base-finder.yml from efendikaptan
        run: |
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
            -X POST \
            -H "Authorization: token ${{ secrets.MY_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"ref": "main"}' \
            https://api.github.com/repos/user/efendikaptan/actions/workflows/base-finder.yml/dispatches)

          echo "Response Code: $RESPONSE"
          cat response.json

      - name: Trigger base-finder.yml from Clone
        run: |
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
            -X POST \
            -H "Authorization: token ${{ secrets.MY_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"ref": "main"}' \
            https://api.github.com/repos/user/Clone/actions/workflows/base-finder.yml/dispatches)

          echo "Response Code: $RESPONSE"
          cat response.json
