name: Trigger Workflows from Other Repos

on:
  schedule:
    - cron: "0 */2 * * *"  # Her 2 saatte bir çalışır
  workflow_dispatch:  # Manuel olarak çalıştırılabilir

jobs:
  trigger-other-repos:
    runs-on: ubuntu-latest

    steps:
      # Clone repo'sunda 'ana-domain.yml' workflow'unu tetiklemek için
      - name: Trigger ana-domain.yml from Clone
        run: |
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
            -X POST \
            -H "Authorization: token ${{ secrets.MY_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"ref": "main"}' \
            https://api.github.com/repos/MDuymaz/Clone/actions/workflows/ana-domain.yml/dispatches)

          echo "Response Code: $RESPONSE"
          cat response.json

      # efendikaptan repo'sunda 'ana-domain.yml' workflow'unu tetiklemek için
      - name: Trigger ana-domain.yml from efendikaptan
        run: |
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
            -X POST \
            -H "Authorization: token ${{ secrets.MY_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"ref": "main"}' \
            https://api.github.com/repos/MDuymaz/efendikaptan/actions/workflows/ana-domain.yml/dispatches)

          echo "Response Code: $RESPONSE"
          cat response.json

      # goltv repo'sunda 'ana-domain.yml' workflow'unu tetiklemek için
      - name: Trigger ana-domain.yml from goltv
        run: |
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
            -X POST \
            -H "Authorization: token ${{ secrets.MY_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"ref": "main"}' \
            https://api.github.com/repos/MDuymaz/goltv/actions/workflows/ana-domain.yml/dispatches)

          echo "Response Code: $RESPONSE"
          cat response.json
