name: Trigger Workflows from Other Repos

on:
  schedule:
    - cron: "0 */2 * * *"  # Her 2 saatte bir çalışır
  workflow_dispatch:  # Manuel olarak çalıştırılabilir

jobs:
  trigger-other-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger base-finder.yml from efendikaptan
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.MY_PAT }}" \
            -d '{"ref": "main"}' \
            https://api.github.com/repos/user/efendikaptan/actions/workflows/base-finder.yml/dispatches

      - name: Trigger base-finder.yml from Clone
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.MY_PAT }}" \
            -d '{"ref": "main"}' \
            https://api.github.com/repos/user/Clone/actions/workflows/base-finder.yml/dispatches
